adb pull /system/lib/libaiui.so .
adb pull /system/lib/libalsa-jni.so .
adb pull /system/lib/libbacktrace.so .
adb pull /system/lib/libbase.so .
adb pull /system/lib/libc++.so .
adb pull /system/lib/libcae-jni.so .
adb pull /system/lib/libcutils.so .
adb pull /system/lib/liblzma.so .
adb pull /system/lib/libssl.so .
adb pull /system/lib/libtinyalsa.so .
adb pull /system/lib/libunwind.so .
adb pull /system/lib/libutils.so .
adb pull /system/lib/libvtn.so .